# Generated by Django 2.1.4 on 2019-02-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_disk_manufactory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nic',
            name='macaddress',
            field=models.CharField(max_length=64, verbose_name='MAC'),
        ),
    ]
