# Generated by Django 2.1.4 on 2019-02-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20190216_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=128, verbose_name='token'),
        ),
    ]
